[package]
name = "moodtracker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
confy = "0.6"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["clock"] }
rfd = "0.14"
printpdf = "0.5"
